language: r
r:
  - oldrel
  - release
os:
  - linux
  - osx
dist:
  - bionic
cache: packages
r_packages:
  - covr

before_install:
if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    - tlmgr install inconsolata
fi

after_success:
  - Rscript -e 'library(covr); codecov()'
